// src/components/Footer.vue
<template>
  <footer class="border-t border-border/20 py-12 md:py-16 bg-black">
    <div class="max-w-6xl mx-auto px-6">

      <div class="flex flex-col md:flex-row items-center justify-between gap-6">

        <!-- Logo -->
        <div class="flex items-center gap-2">
          <div class="w-6 h-6 rounded-full bg-primary/20 flex items-center justify-center">
            <div class="w-2 h-2 rounded-full bg-primary" />
          </div>

          <a href="#home" class="font-serif text-lg italic text-foreground">
            Revivo
          </a>
        </div>

        <!-- Links -->
        <div class="flex items-center gap-8">
          <a href="#features" class="text-muted-foreground hover:text-foreground transition-colors text-sm font-sans">
            {{ t('nav.features') }}
          </a>

          <a href="#pricing" class="text-muted-foreground hover:text-foreground transition-colors text-sm font-sans">
            {{ t('nav.pricing') }}
          </a>

          <a href="#stories" class="text-muted-foreground hover:text-foreground transition-colors text-sm font-sans">
            {{ t('nav.stories') }}
          </a>
        </div>

        <!-- Copyright -->
        <p class="font-sans text-muted-foreground text-xs">
          © {{ year }} Revivo. {{ t('footer.madeWith') }}
        </p>

      </div>

    </div>
  </footer>
</template>

<script setup>
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

const year = new Date().getFullYear()
</script>

// src/components/reactCode/Footer.jsx
export default function Footer() {
  return (
    <footer className="border-t border-border/20 py-12 md:py-16">
      <div className="max-w-6xl mx-auto px-6">
        <div className="flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 rounded-full bg-primary/20 flex items-center justify-center">
              <div className="w-2 h-2 rounded-full bg-primary" />
            </div>
            <span className="font-serif text-lg italic text-foreground">Revivo</span>
          </div>

          <div className="flex items-center gap-8">
            <a href="#features" className="text-muted-foreground hover:text-foreground transition-colors text-sm font-sans">
              Features
            </a>
            <a href="#pricing" className="text-muted-foreground hover:text-foreground transition-colors text-sm font-sans">
              Pricing
            </a>
            <a href="#stories" className="text-muted-foreground hover:text-foreground transition-colors text-sm font-sans">
              Stories
            </a>
          </div>

          <p className="font-sans text-muted-foreground/40 text-xs">
            © {new Date().getFullYear()} Revivo. Made with memory.
          </p>
        </div>
      </div>
    </footer>
  );
}
